import type { Metadata } from "next";

import "./globals.css";
import { Inconsolata, Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/trpc/client";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import {Toaster} from "@/components/ui/sonner";
const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inconsolata = Inconsolata({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-inconsolata", // 👈 dùng cho global CSS
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
       <TRPCReactProvider>
      <html lang="en" className={cn("font-sans ", geist.variable)}>
        <body className={`${inconsolata.variable} antialiased`}>
          <Toaster />
          {children}
        </body>
      </html>
    </TRPCReactProvider>
    </NuqsAdapter>
   
  );
}
